// Generated by gen_market.py

interface AppManifest {
  metadata: {
    name: string; version: string; icon: string; title: Record<string, string>;
    description: Record<string, string>; categories: string[]; developer: string;
    website?: string; sourceCode?: string; license?: string; supportArch?: string[];
    fullDescription?: string; upgradeDescription?: string; requiredCpu?: string;
    requiredMemory?: string; requiredDisk?: string; requiredGpu?: string;
    limitedCpu?: string; limitedMemory?: string; apiTimeout?: number;
  };
  spec: {
    type: string;
    entrance: { name: string; title: Record<string, string>; port: number; host?: string; authLevel?: string; openMethod?: string }[];
    permission: unknown[]; middleware: unknown[];
    options: { resources: { cpu: string; memory: string; disk: string } };
    envs?: { envName: string; required: boolean; default?: string; type?: string; editable?: boolean; applyOnChange?: boolean; description?: string; options?: { title: string; value: string }[] }[];
  };
}

export const apps: AppManifest[] = [
  {
    metadata: {
      name: "aimllmgemma4vllm",
      version: "2.4.0",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-llmgemma4vllm/main/icon.png",
      title: { en: "AIM Gemma4 26B-A4B vLLM" },
      description: { en: "Gemma 4 26B A4B QAT-AWQ-INT4 via vLLM — optimized for coding & agentic workflows" },
      fullDescription:
        `Gemma 4 26B A4B – Multimodales LLM (Text + Image) mit QAT-AWQ-INT4 Quantisierung auf vLLM.

**Model**
cyankiwi/gemma-4-26B-A4B-it-qat-AWQ-INT4 (QAT + AWQ INT4, ~15 GB).
96K Token Kontext. Multimodal (Text + Image, kein Video).

**Inference Engine**
vLLM v0.23.1rc cu129, SHA-gepinnt (g4080263bb).
fp8 KV-Cache. CUDAGraphs + torch.compile aktiv.
MTP Speculative Decoding (3 Tokens, google/gemma-4-26B-A4B-it-assistant).
GPU VRAM: ~23.0 GB belegt.

**Performance (RTX 5090 Blackwell, MTP Spec-Decoding)**
- Coding (2000 tok): ~419 tok/s
- Creative (2000 tok): ~280 tok/s
- Needle Haystack: 25/25 (100%)
- Agentic Tool-Calling: 8/8 (100%)

**API**
OpenAI-kompatibel: /v1/chat/completions, /v1/models, /health.
Tool Calling via --enable-auto-tool-choice + --tool-call-parser gemma4.
Reasoning via --reasoning-parser gemma4 + --default-chat-template-kwargs enable_thinking.

**Resource Usage**
GPU: ~22.5 GB VRAM belegt (RTX 5090, 24 GB total)
RAM: 24-40 GB
Disk: 50 GB (Model-Download ~15 GB + Cache)
CPU: 4-16 Kerne`,
      upgradeDescription:
        `v2.4.0: MTP Speculative Decoding reaktiviert. CUDAGraphs + torch.compile — 419 tok/s Coding, 280 tok/s Poetry (3.5x schneller). enforce-eager entfernt, chunked-prefill entfernt, VLLM_USE_FLASHINFER_SAMPLER=0. MAX_MODEL_LEN 200k→96k (V1 Engine 28 KiB/Tok vs V0 14 KiB, MTP + CUDAGraphs passen nicht in 24 GB). Needle 100%, Agentic 100%. v2.3.0: Voller 200K-Kontext zurueck — hybride SWA-Amortisation (5 Full-Attention-Layer, Pool 267k Tokens). v2.2.2: Olares 1.12.6 Reparatur — SHA-gepinnter cu129-nightly g4080263bb. video:0, batch 8192, util 0.98.`,
      categories: ["LLM Chat"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-llmgemma4vllm",
      sourceCode: "https://github.com/bayerhazard/aimighty-llmgemma4vllm",
      supportArch: ["amd64"],
      requiredCpu: "4",
      requiredMemory: "24Gi",
      requiredDisk: "50Gi",
      requiredGpu: "1",
      limitedCpu: "16",
      limitedMemory: "40Gi",
      apiTimeout: 3600,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimllmgemma4vllm", title: { en: "AIM Gemma4 26B-A4B vLLM" }, port: 8000, host: "aimllmgemma4vllm", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "4", memory: "24Gi", disk: "50Gi" } },
    },
  },
  {
    metadata: {
      name: "aimembqwen3vino",
      version: "1.7.1",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-embedder/main/icon.png",
      title: { en: "AIM Qwen3 Embedding" },
      description: { en: "Qwen3-Embedding-4B INT8 via OpenVINO" },
      fullDescription:
        `Qwen3-Embedding-4B + OpenVINO on CPU, optimized for Olares One.

**Model**
Qwen/Qwen3-Embedding-4B — a 4-billion-parameter embedding model from Qwen, INT8 quantized via Optimum Intel for efficient inference on consumer hardware.

**Inference Engine**
OpenVINO 2026.0.0+ with Hugging Face Transformers 4.55.4. Runs on Intel Core Ultra iGPU (Arrow Lake-S) with automatic CPU fallback.

**Key Features**
- OpenAI-compatible API endpoints: /v1/embeddings, /v1/models, /health
- THROUGHPUT mode with 2 parallel streams
- Async endpoints with race-condition protection
- Cluster mode (2 pods) or single-node mode selectable at install time
- Built-in HTML dashboard on root endpoint (/)

**Resource Usage**
Single mode: ~24 GB RAM, 2 CPU cores
Cluster mode: ~48 GB RAM, 4 CPU cores (2 nodes)
Disk: 50 GB for model cache`,
      upgradeDescription:
        `v1.7.0: accelerator: [{mode: cpu}] ergänzt (v3 AutoSelectMode: ohne → "No matching GPU type" 400). v1.6.9: replicas via .Values.workloads.aimembqwen3vino.replicaCount (v3-Validation). v1.6.8: Olares-Dependency >=1.12.6-0 (v3 erfordert es). v1.6.7: Migrate OlaresManifest v2 → v3 (app-service lehnt apiVersion v2 ab, HTTP 403). v1.6.6: Version alignment + sauberes Chart-Packaging. v1.6.5: Fixed deployment title. v1.6.4: Renamed to 'AIM Qwen3 Embedding'. v1.6.2: Simplified deployment (Recreate), fixed pod anti-affinity deadlock. v1.5.5: Release v1.5.5. Final naming corrections and entrance status fix. v1.5.1: Fixed app title. v1.5.0: Version bump to force Olares re-sync.`,
      categories: ["AI Agents"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-embedder",
      sourceCode: "https://github.com/bayerhazard/aimighty-embedder",
      supportArch: ["amd64"],
      requiredCpu: "2",
      requiredMemory: "24Gi",
      requiredDisk: "50Gi",
      requiredGpu: "0",
      limitedCpu: "4",
      limitedMemory: "24Gi",
      apiTimeout: 3600,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimembqwen3vino", title: { en: "Qwen3 Embedding" }, port: 9997, host: "aimembqwen3vino", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "2", memory: "24Gi", disk: "50Gi" } },
      envs: [
        { envName: "EMBEDDER_MODE", required: false, default: "cluster", type: "string", editable: true, applyOnChange: true, description: "Deployment mode: 'cluster' = 2 pods across nodes (~48GB RAM), 'single' = 1 pod (~24GB RAM)", options: [{"title": "Cluster mode (2 pods, ~48GB RAM)", "value": "cluster"}, {"title": "Single node (1 pod, ~24GB RAM)", "value": "single"}] },
        { envName: "OV_DEVICE", required: false, default: "CPU", type: "string", editable: true, applyOnChange: true, description: "OpenVINO inference device", options: [{"title": "CPU (recommended)", "value": "CPU"}, {"title": "GPU (requires compatible driver)", "value": "GPU"}] },
        { envName: "PERFORMANCE_HINT", required: false, default: "THROUGHPUT", type: "string", editable: true, applyOnChange: true, description: "OpenVINO performance optimization mode", options: [{"title": "THROUGHPUT (maximize requests/sec)", "value": "THROUGHPUT"}, {"title": "LATENCY (minimize response time)", "value": "LATENCY"}] },
        { envName: "NUM_STREAMS", required: false, default: "2", type: "int", editable: true, applyOnChange: true, description: "Number of parallel inference streams" },
        { envName: "MODEL_NAME", required: false, default: "aimighty-embedding-4b", type: "string", editable: true, applyOnChange: true, description: "Model name exposed in the OpenAI-compatible API" },
      ],
    },
  },
  {
    metadata: {
      name: "aimrerqwen3vllm",
      version: "1.6.5",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-reranker/main/icon.png",
      title: { en: "AIM Qwen3 Reranker" },
      description: { en: "Qwen3-Reranker-0.6B via vllm" },
      fullDescription:
        `Aimighty Reranker deploys Qwen3-Reranker-0.6B using vllm on NVIDIA RTX 5090 (Blackwell).

**Features**
- /v1/rerank endpoint (OpenAI-compatible)
- Live monitoring dashboard on port 8080
- FlashInfer attention backend optimized for SM120
- Prometheus metrics via /metrics
- Optimized: 4 GB GPU, 12 GB RAM`,
      upgradeDescription:
        `v1.6.5: Fixed deployment title to 'Qwen3 Reranker'. v1.6.4: Category update — moved to AI Agents. v1.6.3: Renamed to 'AIM Qwen3 Reranker'. v1.6.2: Fixed chart encoding (was double-gzip, broke Olares tar extraction). v1.6.1: Fixed corrupted chart in market source (base64 truncation). v1.6.0: Version bump to force Olares re-sync with fresh chart encoding. v1.5.5: Release v1.5.5. Final naming corrections and entrance status fix.`,
      categories: ["AI Agents"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-reranker",
      sourceCode: "https://github.com/bayerhazard/aimighty-reranker",
      supportArch: ["amd64"],
      requiredCpu: "1",
      requiredMemory: "4Gi",
      requiredDisk: "10Gi",
      requiredGpu: "1",
      limitedCpu: "4",
      limitedMemory: "12Gi",
      apiTimeout: 3600,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimrerqwen3vllm", title: { en: "Qwen3 Reranker" }, port: 8080, host: "aimrerqwen3vllm", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "1", memory: "4Gi", disk: "10Gi" } },
    },
  },
  {
    metadata: {
      name: "aimrerqwen3vino",
      version: "1.0.3",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-reranker-cpu/main/icon.png",
      title: { en: "AIM Qwen3 Reranker CPU" },
      description: { en: "Qwen3-Reranker-0.6B INT8 via OpenVINO" },
      fullDescription:
        `Qwen3-Reranker-0.6B + OpenVINO on CPU, optimized for Olares One.

**Model**
tomaarsen/Qwen3-Reranker-0.6B-seq-cls — a 600-million-parameter cross-encoder sequence classification model, INT8 quantized via Optimum Intel for efficient CPU inference.

**Inference Engine**
OpenVINO 2026.0.0+ with Hugging Face Transformers 4.55.4. Runs on Intel Core Ultra 9 275HX (Meteor Lake) CPU using Redwood/Golden Cove P-Cores.

**Key Features**
- Jina/Cohere-compatible API endpoints: /v1/rerank, /rerank, /v1/models, /health
- Dynamic shapes, async endpoints, and multicore scaling using OpenVINO TBB
- Automatic model download and OpenVINO conversion on first start
- Built-in HTML dashboard on root endpoint (/)

**Resource Usage**
RAM: 16 GB, CPU: 24 cores
Disk: 10 GB`,
      upgradeDescription:
        `v1.0.3: Fixed deployment title to 'Qwen3 Reranker CPU'. v1.0.2: Category update — moved to AI Agents. v1.0.1: Renamed to 'AIM Qwen3 Reranker CPU'. Fixed icon URL. v1.0.0: Initial stable release. Optimized for Intel Core Ultra 9 275HX hybrid architecture. Unlocked CPU limit to 24 cores. Integrated support for iGPU / NPU hardware routing.`,
      categories: ["AI Agents"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-reranker-cpu",
      sourceCode: "https://github.com/bayerhazard/aimighty-reranker-cpu",
      supportArch: ["amd64"],
      requiredCpu: "4",
      requiredMemory: "16Gi",
      requiredDisk: "10Gi",
      requiredGpu: "0",
      limitedCpu: "24",
      limitedMemory: "16Gi",
      apiTimeout: 3600,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimrerqwen3vino", title: { en: "Qwen3 Reranker CPU" }, port: 8080, host: "aimrerqwen3vino", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "4", memory: "16Gi", disk: "10Gi" } },
    },
  },
  {
    metadata: {
      name: "aimvoxtral4bvllm",
      version: "1.0.3",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-voxtral-4b/main/icon.png",
      title: { en: "AIM Voxtral 4B TTS HQ" },
      description: { en: "Mistral Voxtral 4B TTS via vLLM-Omni — 1 GiB KV-Cache, 10.9 GB VRAM" },
      fullDescription:
        `**Voxtral-4B-TTS** — Mistral's frontier text-to-speech model, served via vLLM-Omni with optimized resource usage.

**Model**
mistralai/Voxtral-4B-TTS-2603 via vLLM-Omni v0.18.0. BF16 precision with 1 GiB KV-Cache reduces VRAM to 10.9 GB (vs 20.5 GB default).

**Inference Engine**
vLLM-Omni with optimized KV-Cache management. OpenAI-compatible API.

**Key Features**
- OpenAI-compatible API: /v1/audio/speech, /v1/models
- 20 preset voices across 10 languages
- 24 kHz audio output
- Optimized: 1 GiB KV-Cache → 10.9 GB VRAM
- Web dashboard for quick testing
- Unlimited API timeout for long TTS responses

**API Example**
bash
curl -X POST http://localhost:8000/v1/audio/speech -H "Content-Type: application/json" -d '{"model": "voxtral-tts-4b", "input": "Hello world!", "voice": "neutral_female"}' -o output.wav

**Note:** Model weights are CC-BY-NC-4.0 (non-commercial use only).`,
      upgradeDescription:
        `v1.0.3: Fixed deployment title to 'Voxtral 4B HQ'. v1.0.2: Category update — moved to Audio. v1.0.1: Fixed OlaresManifest schema (appid, type, entrances), added openMethod: window. v1.0.0: Initial release — vLLM-Omni with optimized KV-Cache (1 GiB), 10.9 GB VRAM, Web Dashboard.`,
      categories: ["Audio"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-voxtral-4b",
      sourceCode: "https://github.com/bayerhazard/aimighty-voxtral-4b",
      supportArch: ["amd64"],
      requiredCpu: "2",
      requiredMemory: "16Gi",
      requiredDisk: "20Gi",
      requiredGpu: "1",
      limitedCpu: "8",
      limitedMemory: "16Gi",
      apiTimeout: 0,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimvoxtral4bvllm", title: { en: "Voxtral 4B HQ" }, port: 8080, host: "aimvoxtral4bvllm", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "2", memory: "16Gi", disk: "20Gi" } },
    },
  },
  {
    metadata: {
      name: "aimvoxtral4tts",
      version: "1.0.10",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-voxtral-tts/main/icon.png",
      title: { en: "AIM Voxtral 4B TTS" },
      description: { en: "Mistral Voxtral 4B TTS int4 — OpenAI-compatible /v1/audio/speech" },
      fullDescription:
        `**Voxtral-4B-TTS** — Mistral's frontier text-to-speech model, int4 quantized for efficient GPU inference.

**Model**
Mistral Voxtral-4B-TTS-2603, quantized to int4 via torchao + HQQ algorithm. Near-lossless quality at 54% VRAM reduction (3.8 GB vs 8 GB BF16).

**Inference Engine**
Custom PyTorch inference with torch.compile optimization. 57 fps audio token generation on RTX 3090/4090/5090.

**Key Features**
- OpenAI-compatible API: /v1/audio/speech, /v1/models, /v1/audio/voices
- 20 preset voices across 9 languages
- 48 kHz audio output in WAV format
- Long text auto-batching (1000 char segments)
- Web dashboard for quick testing

**Resource Usage**
GPU: 1× NVIDIA (3.8 GB VRAM, RTX 3090/4090/5090)
RAM: 4-12 GB
CPU: 2-4 cores
Disk: 15 GB (model pre-baked in image)

**Note:** Model weights are CC-BY-NC-4.0 (non-commercial use only).`,
      upgradeDescription:
        `v1.0.10: Fixed deployment title to 'Voxtral 4B'. v1.0.9: Category update — moved to Audio. v1.0.5: Upgraded to PyTorch 2.12.1+cu126 (sm_120 support for RTX 5090 Laptop) + torchao 0.17.0. Fixed "no kernel image available" CUDA error.`,
      categories: ["Audio"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-voxtral-tts",
      sourceCode: "https://github.com/bayerhazard/aimighty-voxtral-tts",
      supportArch: ["amd64"],
      requiredCpu: "2",
      requiredMemory: "16Gi",
      requiredDisk: "15Gi",
      requiredGpu: "1",
      limitedCpu: "4",
      limitedMemory: "32Gi",
      apiTimeout: 300,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimvoxtral4tts", title: { en: "Voxtral 4B" }, port: 8080, host: "aimvoxtral4tts", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "2", memory: "16Gi", disk: "15Gi" } },
    },
  },
  {
    metadata: {
      name: "aimqwen36llama",
      version: "1.4.1",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-llmqwen36llama/main/icon.png",
      title: { en: "AIM Qwen3.6 27B" },
      description: { en: "Qwen3.6-27B beellama (Aimighty) - UD-Q4_K_XL + Ardenzard IQ4_XS DFlash + turbo3 KV" },
      fullDescription:
        `Qwen3.6-27B beellama (Aimighty) — UD-Q4_K_XL (17.6 GB) + Ardenzard IQ4_XS DFlash (892 MB) on NVIDIA RTX 5090 (24 GiB VRAM).

Optimized for coding and agentic workflows on Olares One. Based on the proven
aamsellem/beellama-cpp:0.1.3-rc1 image (custom sm_120 Blackwell build).

**Model:** unsloth/Qwen3.6-27B-UD-Q4_K_XL (17.6 GB, non-MTP variant)
**Draft:** Ardenzard IQ4_XS (892 MB)
**Engine:** aamsellem/beellama-cpp:0.1.3-rc1 — custom Blackwell sm_120 build
**KV Cache:** turbo3 (3-bit Walsh-Hadamard rotated, scales linearly with context)
**Vision:** mmproj-F16 with CPU offload (--no-mmproj-offload)
**Speculation:** DFlash with --spec-dflash-cross-ctx 1024
**Context:** 200K tokens with prompt cache
**Batch:** 2048 / 512 (processing-optimized)
**Chat Template:** Custom agentic Jinja2 template (think-disabled)
**API:** OpenAI-compatible at port 8000

**Performance (RTX 5090 Blackwell, 24 GiB, 200k ctx):**
- Warm prompt: ~130 t/s
- Text generation: ~44-50 t/s (code burst >200 t/s with DFlash)
- VRAM: ~20.4 GB (83%) — stable with headroom
- Vision: active (clip encoder, CPU offload)`,
      upgradeDescription:
        `v1.4.1: Optimierungen nach Benchmark — Q3_K_XL→Q4_K_XL. IQ4_XS DFlash (+19% code t/s). ubatch 2048→512. ctx-checkpoints 8→4. chat-template-kwargs think-disabled.`,
      categories: ["LLM Chat", "Vision"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-llmqwen36llama",
      sourceCode: "https://github.com/bayerhazard/aimighty-llmqwen36llama",
      supportArch: ["amd64"],
      requiredCpu: "4",
      requiredMemory: "24Gi",
      requiredDisk: "25Gi",
      requiredGpu: "1",
      limitedCpu: "16",
      limitedMemory: "40Gi",
      apiTimeout: 0,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimqwen36llama", title: { en: "AIM Qwen3.6 27B" }, port: 8000, host: "aimqwen36llama", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "16", memory: "40Gi", disk: "50Gi" } },
    },
  },
  {
    metadata: {
      name: "aimqwen3635bllama",
      version: "1.4.0",
      icon: "https://app.cdn.olares.com/appstore/llamacpp/icon2.png",
      title: { "en-US": "AIM Qwen3.6 35B A3B" },
      description: { "en-US": "Qwen3.6-35B-A3B - IQ4_XS - MTP + Vision - Agent-Optimized" },
      fullDescription:
        `Qwen3.6-35B-A3B MoE — an efficient 35B Mixture-of-Experts model
with only ~3B active parameters per token. Served via llama.cpp
(spiritbuun buun-llama-cpp fork) on NVIDIA RTX 5090.

**Key Parameters**
- Quant: UD-IQ4_XS (4-bit, ~18 GB) — superior quality vs Q3
- Spec Decoding: Built-in MTP (3 speculative tokens, no drafter needed)
- Vision: Native via mmproj-gpu-swap (mmproj on CPU, swaps to GPU on image input)
- KV Cache: q8_0 K / turbo4 V (spiritbuun fork)
- Context: 200,000 tokens
- Reasoning: OFF (Agent-optimized — reliable tool-calls, longer sessions)
- Flash Attention: on
- GPU: full offload (-ngl all), 19.9 of 24 GB VRAM used
- Sampling: temp=0.6, top-p=0.95, top-k=20 (Qwen3.6 precise coding)

**Performance (RTX 5090 Blackwell, 24 GB)**
- Text Generation: ~275 tok/s (88.5% MTP acceptance)
- Tool-Calling: reliable from max_tokens=256 (no reasoning budget conflict)
- Vision: ~555ms swap overhead, correct image analysis
- VRAM: 19.9 GB / 24.5 GB (81%)

**API**
OpenAI-compatible: /v1/chat/completions, /v1/models, /health.
Tool Calling via built-in Qwen3 jinja template.
Vision via image_url in content array.
For deep reasoning: set chat_template_kwargs {enable_thinking: true} per request.`,
      upgradeDescription: { "en-US": "v1.4.0: Vision aktiviert (mmproj-gpu-swap). Reasoning OFF (Agent-optimiert: zuverlaessige Tool-Calls). SSL-Rebuild fuer HTTPS image downloads. 275 tok/s, 88.5% MTP, Tool-Calls ab max_tokens=256." },
      appDescription: { "en-US": "Qwen3.6-35B-A3B MoE - IQ4_XS - MTP + Vision - Agent-Optimized" },
      categories: ["LLM Chat", "Vision"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-llmqwen3635ba3b",
      sourceCode: "https://github.com/bayerhazard/aimighty-llmqwen3635ba3b",
      supportArch: ["amd64"],
      requiredCpu: "4",
      requiredMemory: "24Gi",
      requiredDisk: "25Gi",
      requiredGpu: "1",
      limitedCpu: "16",
      limitedMemory: "40Gi",
      apiTimeout: 3600,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimqwen3635bllama", title: { "en-US": "AIM Qwen3.6 35B A3B" }, port: 8000, host: "aimqwen3635bllama", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "4", memory: "24Gi", disk: "25Gi" } },
    },
  },
  {
    metadata: {
      name: "aimqwen36vllm",
      version: "1.1.0",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-llmqwen36vllm/main/icon.png",
      title: { en: "AIM Qwen3.6 27B vLLM" },
      description: { en: "Qwen3.6-27B via vLLM — text-only, TurboQuant-KV, MTP, 175K Kontext" },
      fullDescription:
        `Qwen3.6-27B auf vLLM — Text-only Modell (drawais/Qwen3.6-27B-AWQ-INT4) ohne Vision-Tower.

**Modell:** drawais/Qwen3.6-27B-AWQ-INT4 (Qwen3_5ForCausalLM, ~17.7 GiB VRAM)
**Engine:** vllm/vllm-openai cu129-nightly, SHA-gepinnt (g4080263bb)
**KV-Cache:** TurboQuant 3-bit (turboquant_3bit_nc)
**Speculative Decoding:** natives MTP (spec=2, Acceptance ~84.6%)
**Kontext:** 175K Tokens (kein CPU-Offload)
**Tool-Calling:** qwen3_xml Parser (auto + required)
**Chat-Template:** Custom agentic Jinja2 (multi-turn tool-call Fix)

**Performance (RTX 5090, 24 GiB):**
- Decode: ~65 tok/s (MTP spec=2, kein Offload)
- Prefill: ~325-680 tok/s
- MTP Acceptance: 84.6% (pos0 93.7%, pos1 75.5%)

**API:** OpenAI-kompatibel Port 8000`,
      upgradeDescription:
        `v1.1.0: Text-only Modell (drawais/Qwen3.6-27B-AWQ-INT4) statt cyankiwi/Vision-Variante. Spart ~1.9 GiB (kein Vision-Tower, kein MM-Encoder-Cache). Kontext auf 175K ohne CPU-Offload erhoht. v1.0.2: Coding-optimierte Sampling-Defaults. v1.0.1: Sweet Spot 131k+MTP. v1.0.0: Initialer vLLM-Port.`,
      categories: ["LLM Chat"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-llmqwen36vllm",
      sourceCode: "https://github.com/bayerhazard/aimighty-llmqwen36vllm",
      supportArch: ["amd64"],
      requiredCpu: "4",
      requiredMemory: "24Gi",
      requiredDisk: "50Gi",
      requiredGpu: "1",
      limitedCpu: "16",
      limitedMemory: "40Gi",
      apiTimeout: 3600,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimqwen36vllm", title: { en: "AIM Qwen3.6 27B vLLM" }, port: 8000, host: "aimqwen36vllm", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "4", memory: "24Gi", disk: "50Gi" } },
      envs: [
        { envName: "HF_TOKEN", required: false, applyOnChange: true, description: "Hugging Face token for model download" },
      ],
    },
  },
  {
    metadata: {
      name: "wings",
      version: "1.9.1",
      icon: "https://raw.githubusercontent.com/bayerhazard/wings-for-hermes/main/icon.png",
      title: { en: "Wings for Hermes" },
      description: { en: "Wings for Hermes — AI Agent Web UI, runs agent in-process like hermes-webui" },
      fullDescription:
        `**Wings for Hermes** — AI Agent Web UI with premium redesign, curated skins, and auto-detection of Hermes Agent home.

**Full CLI parity** — everything you can do from the Hermes terminal:
- Chat with streaming, reasoning display, tool-call cards, approvals
- Sessions: create, resume, search, pin, archive, projects, export
- Memory: view and edit MEMORY.md / USER.md inline
- Skills: list, preview, create, edit, delete
- Tasks: cron jobs — view, create, edit, run, pause/resume, run history
- Profiles, workspaces with file browser, todos, themes

**Shared-state architecture**
Runs on the *same* HERMES_HOME as your Hermes Agent app. Sessions, memory, auth, and config are shared.

**Auto-detection**
Automatically finds your Hermes Agent home directory on startup — no manual configuration needed.

**Requirements**
- Requires the Hermes Agent app (hermesagent) installed for the same Olares user.
- Upstream project: https://github.com/nesquena/hermes-webui (MIT)`,
      upgradeDescription:
        `v1.8.0: Fixed assistant chat layout — tool calls and chat answer now stack vertically (were rendering in one horizontal line).`,
      categories: ["AI"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/wings-for-hermes",
      sourceCode: "https://github.com/bayerhazard/wings-for-hermes",
      supportArch: ["amd64"],
      requiredCpu: "1",
      requiredMemory: "2Gi",
      requiredDisk: "5Gi",
      requiredGpu: "0",
      limitedCpu: "4",
      limitedMemory: "8Gi",
      apiTimeout: 0,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "wings", title: { en: "Wings for Hermes" }, port: 8787, host: "wings", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "1", memory: "2Gi", disk: "5Gi" } },
      envs: [
        { envName: "HERMES_WEBUI_PASSWORD", required: false, type: "password", editable: true, applyOnChange: true, description: "Optional app-level password for the Web UI (in addition to Olares SSO). Recommended when exposing beyond LAN." },
        { envName: "HERMES_WEBUI_DEFAULT_MODEL", required: false, default: "Agent", type: "string", editable: true, applyOnChange: true, description: "Default model name used for new chats (must match a model your Hermes provider key can access, e.g. 'Agent')." },
      ],
    },
  },
];

// redeploy timestamp: 1784998158
// redeploy timestamp: 1785135864