// Generated by gen_market.py

interface AppManifest {
  metadata: {
    name: string; version: string; icon: string; title: Record<string, string>;
    description: Record<string, string>; categories: string[]; developer: string;
    website?: string; sourceCode?: string; license?: string; supportArch?: string[];
    fullDescription?: string; upgradeDescription?: string; requiredCpu?: string;
    requiredMemory?: string; requiredDisk?: string; requiredGpu?: string;
    limitedCpu?: string; limitedMemory?: string; apiTimeout?: number;
  };
  spec: {
    type: string;
    entrance: { name: string; title: Record<string, string>; port: number; host?: string; authLevel?: string; openMethod?: string }[];
    permission: unknown[]; middleware: unknown[];
    options: { resources: { cpu: string; memory: string; disk: string } };
    envs?: { envName: string; required: boolean; default?: string; type?: string; editable?: boolean; applyOnChange?: boolean; description?: string; options?: { title: string; value: string }[] }[];
  };
}

export const apps: AppManifest[] = [
  {
    metadata: {
      name: "aimllmgemma4vllm",
      version: "2.1.2",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-llmgemma4vllm/main/icon.png",
      title: { en: "AIM Gemma4 26B-A4B vLLM" },
      description: { en: "Gemma 4 26B A4B QAT-AWQ-INT4 + MTP Speculative Decoding via vLLM — optimized for coding & agentic workflows" },
      fullDescription:
        `Gemma 4 26B A4B – Multimodales LLM (Text + Image) mit QAT-AWQ-INT4 Quantisierung und MTP Speculative Decoding auf vLLM.

**Model**
cyankiwi/gemma-4-26B-A4B-it-qat-AWQ-INT4 (QAT + AWQ INT4, ~15 GB).
MTP Speculative Decoding mit google/gemma-4-26B-A4B-it-assistant (3 spekulative Tokens).
200K Token Kontext. Multimodal (Text + Image).

**Inference Engine**
vLLM v0.23.0 mit triton_attn Backend. CUDA 13.1 (RTX 5090 Blackwell SM12.0).
fp8 KV-Cache. GPU VRAM: ~22.5 GB belegt.

**Performance (RTX 5090 Blackwell)**
- Short (50 tok): ~133 tok/s
- Medium (500 tok): ~106 tok/s
- Long (2000 tok): ~100+ tok/s
- Vision: ~129 tok/s

**API**
OpenAI-kompatibel: /v1/chat/completions, /v1/models, /health.
Tool Calling via --enable-auto-tool-choice + --tool-call-parser gemma4.
Reasoning via --reasoning-parser gemma4 + --default-chat-template-kwargs enable_thinking.

**Resource Usage**
GPU: ~22.5 GB VRAM belegt (RTX 5090, 24 GB total)
RAM: 24-40 GB
Disk: 50 GB (Model-Download ~15 GB + Cache)
CPU: 4-16 Kerne`,
      upgradeDescription:
        `v1.5.0: Ring track color visible on sidebar bg, session search moved to sidebar footer, ring tooltip on hover only, project pills and color dots hidden in Basic mode.`,
      categories: ["LLM Chat"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-llmgemma4vllm",
      sourceCode: "https://github.com/bayerhazard/aimighty-llmgemma4vllm",
      supportArch: ["amd64"],
      requiredCpu: "4",
      requiredMemory: "24Gi",
      requiredDisk: "50Gi",
      requiredGpu: "1",
      limitedCpu: "16",
      limitedMemory: "40Gi",
      apiTimeout: 3600,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimllmgemma4vllm", title: { en: "AIM Gemma4 26B-A4B vLLM" }, port: 8000, host: "aimllmgemma4vllm", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "4", memory: "24Gi", disk: "50Gi" } },
    },
  },
  {
    metadata: {
      name: "aimembqwen3vino",
      version: "1.6.5",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-embedder/main/icon.png",
      title: { en: "AIM Qwen3 Embedding" },
      description: { en: "Qwen3-Embedding-4B INT8 via OpenVINO" },
      fullDescription:
        `Qwen3-Embedding-4B + OpenVINO on CPU, optimized for Olares One.

**Model**
Qwen/Qwen3-Embedding-4B — a 4-billion-parameter embedding model from Qwen, INT8 quantized via Optimum Intel for efficient inference on consumer hardware.

**Inference Engine**
OpenVINO 2026.0.0+ with Hugging Face Transformers 4.55.4. Runs on Intel Core Ultra iGPU (Arrow Lake-S) with automatic CPU fallback.

**Key Features**
- OpenAI-compatible API endpoints: /v1/embeddings, /v1/models, /health
- THROUGHPUT mode with 2 parallel streams
- Async endpoints with race-condition protection
- Cluster mode (2 pods) or single-node mode selectable at install time
- Built-in HTML dashboard on root endpoint (/)

**Resource Usage**
Single mode: ~24 GB RAM, 2 CPU cores
Cluster mode: ~48 GB RAM, 4 CPU cores (2 nodes)
Disk: 50 GB for model cache`,
      upgradeDescription:
        `v1.6.5: Fixed deployment title to 'Qwen3 Embedding'. v1.6.4: Renamed to 'AIM Qwen3 Embedding'. v1.6.3: Category update — moved to AI Agents. v1.6.2: Version bump to sync with Olares. Simplified deployment — removed rollingUpdate strategy (now Recreate), fixed pod anti-affinity deadlock on restart. v1.5.6: Fixed rolling update strategy (maxSurge=0, maxUnavailable=1) to prevent pod anti-affinity deadlock on restart. Increased revisionHistoryLimit to 3 for rollback safety. v1.5.5: Release v1.5.5. Final naming corrections and entrance status fix. v1.5.1: Fixed app title. v1.5.0: Version bump to force Olares re-sync.`,
      categories: ["AI Agents"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-embedder",
      sourceCode: "https://github.com/bayerhazard/aimighty-embedder",
      supportArch: ["amd64"],
      requiredCpu: "2",
      requiredMemory: "24Gi",
      requiredDisk: "50Gi",
      requiredGpu: "0",
      limitedCpu: "4",
      limitedMemory: "24Gi",
      apiTimeout: 3600,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimembqwen3vino", title: { en: "Qwen3 Embedding" }, port: 9997, host: "aimembqwen3vino", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "2", memory: "24Gi", disk: "50Gi" } },
      envs: [
        { envName: "EMBEDDER_MODE", required: false, default: "cluster", type: "string", editable: true, applyOnChange: true, description: "Deployment mode: 'cluster' = 2 pods across nodes (~48GB RAM), 'single' = 1 pod (~24GB RAM)", options: [{"title": "Cluster mode (2 pods, ~48GB RAM)", "value": "cluster"}, {"title": "Single node (1 pod, ~24GB RAM)", "value": "single"}] },
        { envName: "OV_DEVICE", required: false, default: "CPU", type: "string", editable: true, applyOnChange: true, description: "OpenVINO inference device", options: [{"title": "CPU (recommended)", "value": "CPU"}, {"title": "GPU (requires compatible driver)", "value": "GPU"}] },
        { envName: "PERFORMANCE_HINT", required: false, default: "THROUGHPUT", type: "string", editable: true, applyOnChange: true, description: "OpenVINO performance optimization mode", options: [{"title": "THROUGHPUT (maximize requests/sec)", "value": "THROUGHPUT"}, {"title": "LATENCY (minimize response time)", "value": "LATENCY"}] },
        { envName: "NUM_STREAMS", required: false, default: "2", type: "int", editable: true, applyOnChange: true, description: "Number of parallel inference streams" },
        { envName: "MODEL_NAME", required: false, default: "aimighty-embedding-4b", type: "string", editable: true, applyOnChange: true, description: "Model name exposed in the OpenAI-compatible API" },
      ],
    },
  },
  {
    metadata: {
      name: "aimrerqwen3vllm",
      version: "1.6.5",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-reranker/main/icon.png",
      title: { en: "AIM Qwen3 Reranker" },
      description: { en: "Qwen3-Reranker-0.6B via vllm" },
      fullDescription:
        `Aimighty Reranker deploys Qwen3-Reranker-0.6B using vllm on NVIDIA RTX 5090 (Blackwell).

**Features**
- /v1/rerank endpoint (OpenAI-compatible)
- Live monitoring dashboard on port 8080
- FlashInfer attention backend optimized for SM120
- Prometheus metrics via /metrics
- Optimized: 4 GB GPU, 12 GB RAM`,
      upgradeDescription:
        `v1.6.5: Fixed deployment title to 'Qwen3 Reranker'. v1.6.4: Category update — moved to AI Agents. v1.6.3: Renamed to 'AIM Qwen3 Reranker'. v1.6.2: Fixed chart encoding (was double-gzip, broke Olares tar extraction). v1.6.1: Fixed corrupted chart in market source (base64 truncation). v1.6.0: Version bump to force Olares re-sync with fresh chart encoding. v1.5.5: Release v1.5.5. Final naming corrections and entrance status fix.`,
      categories: ["AI Agents"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-reranker",
      sourceCode: "https://github.com/bayerhazard/aimighty-reranker",
      supportArch: ["amd64"],
      requiredCpu: "1",
      requiredMemory: "4Gi",
      requiredDisk: "10Gi",
      requiredGpu: "1",
      limitedCpu: "4",
      limitedMemory: "12Gi",
      apiTimeout: 3600,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimrerqwen3vllm", title: { en: "Qwen3 Reranker" }, port: 8080, host: "aimrerqwen3vllm", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "1", memory: "4Gi", disk: "10Gi" } },
    },
  },
  {
    metadata: {
      name: "aimrerqwen3vino",
      version: "1.0.3",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-reranker-cpu/main/icon.png",
      title: { en: "AIM Qwen3 Reranker CPU" },
      description: { en: "Qwen3-Reranker-0.6B INT8 via OpenVINO" },
      fullDescription:
        `Qwen3-Reranker-0.6B + OpenVINO on CPU, optimized for Olares One.

**Model**
tomaarsen/Qwen3-Reranker-0.6B-seq-cls — a 600-million-parameter cross-encoder sequence classification model, INT8 quantized via Optimum Intel for efficient CPU inference.

**Inference Engine**
OpenVINO 2026.0.0+ with Hugging Face Transformers 4.55.4. Runs on Intel Core Ultra 9 275HX (Meteor Lake) CPU using Redwood/Golden Cove P-Cores.

**Key Features**
- Jina/Cohere-compatible API endpoints: /v1/rerank, /rerank, /v1/models, /health
- Dynamic shapes, async endpoints, and multicore scaling using OpenVINO TBB
- Automatic model download and OpenVINO conversion on first start
- Built-in HTML dashboard on root endpoint (/)

**Resource Usage**
RAM: 16 GB, CPU: 24 cores
Disk: 10 GB`,
      upgradeDescription:
        `v1.0.3: Fixed deployment title to 'Qwen3 Reranker CPU'. v1.0.2: Category update — moved to AI Agents. v1.0.1: Renamed to 'AIM Qwen3 Reranker CPU'. Fixed icon URL. v1.0.0: Initial stable release. Optimized for Intel Core Ultra 9 275HX hybrid architecture. Unlocked CPU limit to 24 cores. Integrated support for iGPU / NPU hardware routing.`,
      categories: ["AI Agents"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-reranker-cpu",
      sourceCode: "https://github.com/bayerhazard/aimighty-reranker-cpu",
      supportArch: ["amd64"],
      requiredCpu: "4",
      requiredMemory: "16Gi",
      requiredDisk: "10Gi",
      requiredGpu: "0",
      limitedCpu: "24",
      limitedMemory: "16Gi",
      apiTimeout: 3600,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimrerqwen3vino", title: { en: "Qwen3 Reranker CPU" }, port: 8080, host: "aimrerqwen3vino", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "4", memory: "16Gi", disk: "10Gi" } },
    },
  },
  {
    metadata: {
      name: "aimvoxtral4bvllm",
      version: "1.0.3",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-voxtral-4b/main/icon.png",
      title: { en: "AIM Voxtral 4B TTS HQ" },
      description: { en: "Mistral Voxtral 4B TTS via vLLM-Omni — 1 GiB KV-Cache, 10.9 GB VRAM" },
      fullDescription:
        `**Voxtral-4B-TTS** — Mistral's frontier text-to-speech model, served via vLLM-Omni with optimized resource usage.

**Model**
mistralai/Voxtral-4B-TTS-2603 via vLLM-Omni v0.18.0. BF16 precision with 1 GiB KV-Cache reduces VRAM to 10.9 GB (vs 20.5 GB default).

**Inference Engine**
vLLM-Omni with optimized KV-Cache management. OpenAI-compatible API.

**Key Features**
- OpenAI-compatible API: /v1/audio/speech, /v1/models
- 20 preset voices across 10 languages
- 24 kHz audio output
- Optimized: 1 GiB KV-Cache → 10.9 GB VRAM
- Web dashboard for quick testing
- Unlimited API timeout for long TTS responses

**API Example**
bash
curl -X POST http://localhost:8000/v1/audio/speech -H "Content-Type: application/json" -d '{"model": "voxtral-tts-4b", "input": "Hello world!", "voice": "neutral_female"}' -o output.wav

**Note:** Model weights are CC-BY-NC-4.0 (non-commercial use only).`,
      upgradeDescription:
        `v1.0.3: Fixed deployment title to 'Voxtral 4B HQ'. v1.0.2: Category update — moved to Audio. v1.0.1: Fixed OlaresManifest schema (appid, type, entrances), added openMethod: window. v1.0.0: Initial release — vLLM-Omni with optimized KV-Cache (1 GiB), 10.9 GB VRAM, Web Dashboard.`,
      categories: ["Audio"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-voxtral-4b",
      sourceCode: "https://github.com/bayerhazard/aimighty-voxtral-4b",
      supportArch: ["amd64"],
      requiredCpu: "2",
      requiredMemory: "16Gi",
      requiredDisk: "20Gi",
      requiredGpu: "1",
      limitedCpu: "8",
      limitedMemory: "16Gi",
      apiTimeout: 0,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimvoxtral4bvllm", title: { en: "Voxtral 4B HQ" }, port: 8080, host: "aimvoxtral4bvllm", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "2", memory: "16Gi", disk: "20Gi" } },
    },
  },
  {
    metadata: {
      name: "aimvoxtral4tts",
      version: "1.0.10",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-voxtral-tts/main/icon.png",
      title: { en: "AIM Voxtral 4B TTS" },
      description: { en: "Mistral Voxtral 4B TTS int4 — OpenAI-compatible /v1/audio/speech" },
      fullDescription:
        `**Voxtral-4B-TTS** — Mistral's frontier text-to-speech model, int4 quantized for efficient GPU inference.

**Model**
Mistral Voxtral-4B-TTS-2603, quantized to int4 via torchao + HQQ algorithm. Near-lossless quality at 54% VRAM reduction (3.8 GB vs 8 GB BF16).

**Inference Engine**
Custom PyTorch inference with torch.compile optimization. 57 fps audio token generation on RTX 3090/4090/5090.

**Key Features**
- OpenAI-compatible API: /v1/audio/speech, /v1/models, /v1/audio/voices
- 20 preset voices across 9 languages
- 48 kHz audio output in WAV format
- Long text auto-batching (1000 char segments)
- Web dashboard for quick testing

**Resource Usage**
GPU: 1× NVIDIA (3.8 GB VRAM, RTX 3090/4090/5090)
RAM: 4-12 GB
CPU: 2-4 cores
Disk: 15 GB (model pre-baked in image)

**Note:** Model weights are CC-BY-NC-4.0 (non-commercial use only).`,
      upgradeDescription:
        `v1.0.10: Fixed deployment title to 'Voxtral 4B'. v1.0.9: Category update — moved to Audio. v1.0.5: Upgraded to PyTorch 2.12.1+cu126 (sm_120 support for RTX 5090 Laptop) + torchao 0.17.0. Fixed "no kernel image available" CUDA error.`,
      categories: ["Audio"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-voxtral-tts",
      sourceCode: "https://github.com/bayerhazard/aimighty-voxtral-tts",
      supportArch: ["amd64"],
      requiredCpu: "2",
      requiredMemory: "16Gi",
      requiredDisk: "15Gi",
      requiredGpu: "1",
      limitedCpu: "4",
      limitedMemory: "32Gi",
      apiTimeout: 300,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimvoxtral4tts", title: { en: "Voxtral 4B" }, port: 8080, host: "aimvoxtral4tts", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "2", memory: "16Gi", disk: "15Gi" } },
    },
  },
  {
    metadata: {
      name: "aimqwen36llama",
      version: "2.3.5",
      icon: "https://raw.githubusercontent.com/bayerhazard/aimighty-llmqwen36llama/main/icon.png",
      title: { en: "AIM Qwen3.6 27B Beellama" },
      description: { en: "Qwen3.6-27B beellama - UD-Q4_K_XL - DFlash IQ4_XS - kvarn4 KV - parallel 1 - cache-ram 0" },
      fullDescription:
        `Qwen3.6-27B beellama — UD-Q4_K_XL (17.6 GB) + DFlash IQ4_XS (1 GB) on NVIDIA RTX 5090 (24 GiB VRAM).

Optimized for coding and agentic workflows on Olares One.

**Model**: unsloth/Qwen3.6-27B-UD-Q4_K_XL (7.6 GB, Q4_K_XL quantization)
**Draft**: Anbeeld/Qwen3.6-27B-DFlash-IQ4_XS (1.0 GB, IQ4_XS quantization)
**Engine**: ghcr.io/anbeeld/beellama.cpp:server-cuda-preview-v0.3.2

**Server-side Flags (v2.3.3):**
- --reasoning on --reasoning-budget 4096
- --reasoning-loop-guard force-close
- --reasoning-loop-interventions 2
- --ctx-checkpoints 8
- --ctx-size 200000 --threads 16
- --parallel 1 (ConfigMap-variabel)
- --cache-ram 0 (ConfigMap-variabel, Prompt-Caching deaktiviert)
- --flash-attn on --jinja --no-mmap --mlock
- --batch-size 2048 -ub 512
- check-auth: command ["true"] (immune to app-service webhook overwrite)

**Performance (RTX 5090 Blackwell, 24 GiB, --parallel 2):**
- HTML Space Invaders (2000 tok): ~101 tok/s
- Creative Poem (2000 tok): ~60 tok/s
- Parallel Stress (2 concurrent): 1.46x combined throughput
- Needle Haystack: 96% (24/25)
- Agentic Tool-Calling: 100% (9/9)`,
      upgradeDescription:
                 `v2.3.3: Revert --parallel 2→1, --cache-ram 2048→0 (prompt cache aus — OOM-Risiko bei 2x 200k). Sauberes Release basierend auf v2.3.0 (check-auth command:["true"]). v2.3.0: Fix Olares Webhook compat — check-auth uses command:["true"] so app-service webhook patch is harmless. v2.2.6: Fix HAMi compat — removed nvidia.com/gpumem, check-auth args -it→-t 120, removed CUDA_DEVICE_MEMORY_LIMIT. v2.2.5: --parallel 2 + --cache-ram 2048. v2.0.0: Cleanup — removed reasoning-budget-message, min-tokens 256→512.`,
      categories: ["LLM Chat"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/aimighty-llmqwen36llama",
      sourceCode: "https://github.com/bayerhazard/aimighty-llmqwen36llama",
      supportArch: ["amd64"],
      requiredCpu: "4",
      requiredMemory: "24Gi",
      requiredDisk: "25Gi",
      requiredGpu: "1",
      limitedCpu: "16",
      limitedMemory: "40Gi",
      apiTimeout: 0,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "aimqwen36llama", title: { en: "Qwen3.6 27B" }, port: 8000, host: "aimqwen36llama", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "16", memory: "40Gi", disk: "50Gi" } },
    },
  },
  {
    metadata: {
      name: "wings",
      version: "1.5.0",
      icon: "https://raw.githubusercontent.com/bayerhazard/wings-for-hermes/main/icon.png",
      title: { en: "Wings for Hermes" },
      description: { en: "Wings for Hermes — AI Agent Web UI with premium redesign, refined dark theme, curated skins" },
      fullDescription:
        `**Wings for Hermes** — AI Agent Web UI with premium redesign, curated skins, and auto-detection of Hermes Agent home.

**Full CLI parity** — everything you can do from the Hermes terminal:
- Chat with streaming, reasoning display, tool-call cards, approvals
- Sessions: create, resume, search, pin, archive, projects, export
- Memory: view and edit MEMORY.md / USER.md inline
- Skills: list, preview, create, edit, delete
- Tasks: cron jobs — view, create, edit, run, pause/resume, run history
- Profiles, workspaces with file browser, todos, themes

**Shared-state architecture**
Runs on the *same* HERMES_HOME as your Hermes Agent app. Sessions, memory, auth, and config are shared.

**Auto-detection**
Automatically finds your Hermes Agent home directory on startup — no manual configuration needed.

**Requirements**
- Requires the Hermes Agent app (hermesagent) installed for the same Olares user.
- Upstream project: https://github.com/nesquena/hermes-webui (MIT)`,
      upgradeDescription:
        `v1.4.7: Auto-detect Hermes Agent home path — no manual configuration needed. hermesagent dependency declared. UID/GID auto-detected.`,
      categories: ["AI"],
      developer: "Aimighty",
      website: "https://github.com/bayerhazard/wings-for-hermes",
      sourceCode: "https://github.com/bayerhazard/wings-for-hermes",
      supportArch: ["amd64"],
      requiredCpu: "1",
      requiredMemory: "2Gi",
      requiredDisk: "5Gi",
      requiredGpu: "0",
      limitedCpu: "4",
      limitedMemory: "8Gi",
      apiTimeout: 0,
    },
    spec: {
      type: "app",
      entrance: [
        { name: "wings", title: { en: "Wings for Hermes" }, port: 8787, host: "wings", authLevel: "internal", openMethod: "window" },
      ],
      permission: [],
      middleware: [],
      options: { resources: { cpu: "1", memory: "2Gi", disk: "5Gi" } },
      envs: [
        { envName: "HERMES_WEBUI_PASSWORD", required: false, type: "password", editable: true, applyOnChange: true, description: "Optional app-level password for the Web UI (in addition to Olares SSO). Recommended when exposing beyond LAN." },
        { envName: "HERMES_WEBUI_DEFAULT_MODEL", required: false, default: "Agent", type: "string", editable: true, applyOnChange: true, description: "Default model name used for new chats (must match a model your Hermes provider key can access, e.g. 'Agent')." },
      ],
    },
  },
];
